date2_11_zhuce/App01/urls.py
from django.urls import path

from App01 import views, ttt

app_name='App01'
urlpatterns = [
    path('register/',views.register,name='register'),
    # 第三方验证码
    path('verify/', views.verify, name='verify'),
    # 发送短信验证码
    path('sms/',views.send_sms,name='sms'),

    # 短信登录
    path('smslogin/',views.sms_login,name='smslogin'),
    #邮件发送
    # path('sendone/',views.send_one,name='one'),
]

date2_11_zhuce/date2_11_zhuce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('App01/',include('App01.urls')),
    # 在跟路由添加验证码的路由
    path('captcha/',include("captcha.urls")),
]

date2_11_zhuce/App01/models.py
from django.contrib.auth.models import AbstractUser


# Create your models here.
from django.db import models


class User(AbstractUser):
    # username=models.CharField(max_length=30)
    password=models.CharField(max_length=128)
    email=models.CharField(max_length=30)
    phone=models.CharField(max_length=20)

    class Meta:
        db_table='user'

date2_11_zhuce/App01/forms.py
#注册表单
import re

from captcha.fields import CaptchaField
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from App01.models import User
def check_password(Value):
    if re.match(r'\d*$',Value):
        raise ValidationError('密码不能是纯数字')

class RegisterForm(forms.Form):
    username=forms.CharField(label='用户名',min_length=6,required=True,
                             error_messages={'required':'用户名不能为空','min_length':'用户名长度必须大于6位'})
    password=forms.CharField(label='密码',min_length=6,max_length=12,
                             required=True,
                             # validators=[RegexValidator(regex=r'\d*$', message="密码不能是纯数字",code='password')],
                             validators=[check_password],
                             error_messages={'min_length':'密码长度必须大于6，小于12','max_length':'密码长度必须大于6，小于12','required':'密码不能为空'})
    confirm_password = forms.CharField(label='确认密码', min_length=6, max_length=12,
                               required=True,
                               validators=[check_password],
                               error_messages={'min_length': '密码长度必须大于6，小于12', 'max_length': '密码长度必须大于6，小于12',
                                               'required': '密码不能为空'})
    email = forms.EmailField(error_messages={'invalid':'邮箱格式不正确'})
    phone=forms.CharField(label='手机号',min_length=11,max_length=11,
                          required=True,
                          validators=[RegexValidator(regex=r"^1[35678]\d{9}$",message='手机号格式不对',code='phone')],
                          error_messages={'min_length':'手机号必须11位','max_length':'手机号必须11位',
                                          'required':'手机号不能为空'})

    def clean_username(self):
        # 获取用户名
        username = self.cleaned_data.get('username')
        # 查询数据库
        # 如果存在
        if User.objects.filter(username=username).first():
            raise ValidationError("用户名重复")
        # 必须把正确数据返回
        return username

    def clean_phone(self):
        # 获取用户名
        phone = self.cleaned_data.get('phone')
        # 查询数据库
        # 如果存在
        if User.objects.filter(phone=phone).first():
            raise ValidationError("手机号已存在")
        # 必须把正确数据返回
        return phone
    def clean_email(self):
        email=self.cleaned_data.get('email')
        if User.objects.filter(email=email).first():
            raise ValidationError('邮箱已存在')
        return email

    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        # 判断两者是否相等
        if password != confirm_password:
            raise ValidationError({'confirm_password':["两次密码输入不一致"]})
        return self.cleaned_data


# 登录
class LoginForm(forms.Form):
    username = forms.CharField(required=True,error_messages={
        'required':'用户名必须输入'
    })
    password = forms.CharField()
    captcha = CaptchaField()  # 验证码字段

# class SMSlogin(forms.Form):
#     username = forms.CharField(required=True, error_messages={
#         'required': '用户名必须输入'
#     })
#     password = forms.CharField()
#     phone = forms.CharField()
#

date2_11_zhuce/App01/views.py
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from date2_11_zhuce.settings import EMAIL_HOST_USER
# Create your views here.
from django.urls import reverse

from App01.forms import RegisterForm, LoginForm
from App01.models import User


def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            email=form.cleaned_data.get('email')
            phone=form.cleaned_data.get('phone')
            user=User(username=username,password=password,email=email,phone=phone)
            print(username,password,email,phone)

            send_status=send_mail("新用户注册", "欢迎{username}的加入".format(username=username), EMAIL_HOST_USER, ['{email}'.format(email=email),'1239918690@qq.com'])
            print(send_status)
            if send_status:
                user.save()
                return redirect(reverse('App01:verify'))
            else:
                return HttpResponse('邮件发送失败,请稍后重新注册')
        else:
            return render(request,'register.html',locals())

    return render(request,'register.html')


def verify(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        # 验证
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=User.objects.filter(username=username,password=password).first()
            if user:
                return HttpResponse("验证通过")
            else:
                return HttpResponse('用户不存在')
        else:
            return render(request, 'login.html', locals())

    form = LoginForm()
    return render(request,'login.html',locals())


def send_sms(request):
    from App01.SMS import sms
    from random import randint
    # 判断是ajax请求
    if request.is_ajax():
        # 获取手机号
        phone = request.POST.get('phone')
        # 生成随机验证码
        code = randint(1000, 9999)
        # 把验证码存入session
        request.session['code'] = code
        request.session.set_expiry(20*60)  # 1200秒后失效

        # 拼接模板参数
        param = "{'number':%d}" % code
        # 发送
        res = sms.send(phone, param)
        print(code,phone)
        return JsonResponse({'code':1})
    else :
        # 生成随机验证码
        code = randint(1000,9999)
        # 拼接模板参数
        param = "{'number':%d}" % code
        # 发送
        res = sms.send('17852365173',param)
        print(res)
        print(type(res))
        return HttpResponse("已发送{}".format({code}))


def sms_login(request):
    if request.method == 'POST':
        # 验证短信验证码
        yzm = request.POST.get('yzm')
        # 从session获取存入验证码
        code = str(request.session.get('code'))
        print(code, yzm)
        print(type(code), type(yzm))
        if yzm == code:
            username=request.POST.get('username')
            password=request.POST.get('password')
            phone=request.POST.get('phone')
            user=User.objects.filter(username=username,password=password,phone=phone).first()
            if user:
                return HttpResponse("验证成功")
            else:
                return HttpResponse("用户不存在")

    return render(request,'sms.html')


# def send_one(request):
#     send_mail("武汉加油", "中国加油", EMAIL_HOST_USER, ['1239918690@qq.com'])
#     return HttpResponse("发送成功")

date2_11_zhuce/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="{% url 'App01:verify' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username"> <span>{{ form.username.errors.0 }}</span> <br>
    密码：<input type="password" name="password"> <br>
    验证码：{{ form.captcha }} <span>{{ form.captcha.errors.0 }}</span> <br>
    <input type="submit">
</form>
</body>
</html>

date2_11_zhuce/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="{% url 'App01:register' %}" method="post">
    {% csrf_token %}

    用户名：<input type="text" name="username"> <span>{{ form.username.errors }}</span><br>
    密码：<input type="password" name="password">
    <span>{{ form.password.errors }}</span><br>
    确认密码：<input type="password" name="confirm_password"> <span>{{ form.confirm_password.errors }}</span><br>
    邮箱：<input type="text" name="email"> <span>{{form.email.errors}}</span><br>
    手机号：<input type="text" name="phone"> <span>{{form.phone.errors}}</span><br>
    {{ form.errors }}
    <input type="submit">
</form>

</body>
</html>

date2_11_zhuce/templates/sms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>短信登录</title>
</head>
<body>
<form action="{% url 'App01:smslogin' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username"> <br>
    密码：<input type="password" name="password"> <br>
    手机号：<input type="text" name="phone" id="phone"> <br>
    验证码：<input type="text" name="yzm"> <input type="button" id="send" value="发送短信验证码"> <br>
    <input type="submit">
</form>
</body>
</html>
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script>
    $("#send").click(function () {
        num = 5;
        $(this).attr('disabled',true);
        $(this).prop('value',""+num+"秒后发送");
        let _this = this;  //this表示当前按钮
        var timer = setInterval(function () {
            num -= 1;
            if (num <=0){
                $(_this).attr('disabled',false);
                $(this).prop('value',"发送验证码")
                return
            }
            $(_this).prop('value',""+num+"秒后发送");
            console.log(num)
        },1000);
        let phone = $("#phone").val();
        let csrf = $("[name='csrfmiddlewaretoken']").val();
        // 发送短信验证码
        $.post("{% url 'App01:sms' %}",{'phone':phone,'csrfmiddlewaretoken':csrf},function (data) {
            console.log(data)
        })

    })
</script>